[package]
name = "libcw"
version = "0.1.0"
authors = ["Will Johnston <wbjohnston@gmail.com>"]

[features]
default = ["parser", "mars"]
parser = ["regex", "lazy_static"]
mars = []

[dependencies]
regex = { version = "0.2", optional = true}
lazy_static = { version = "0.2", optional = true}
