(function() {var implementors = {};
implementors["libcw"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libcw/redcode/types/enum.OpCode.html\" title=\"enum libcw::redcode::types::OpCode\">OpCode</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libcw/redcode/types/enum.Modifier.html\" title=\"enum libcw::redcode::types::Modifier\">Modifier</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libcw/redcode/types/enum.AddressingMode.html\" title=\"enum libcw::redcode::types::AddressingMode\">AddressingMode</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"libcw/redcode/struct.Instruction.html\" title=\"struct libcw::redcode::Instruction\">Instruction</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libcw/simulation/enum.SimulationError.html\" title=\"enum libcw::simulation::SimulationError\">SimulationError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libcw/simulation/enum.LoadError.html\" title=\"enum libcw::simulation::LoadError\">LoadError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libcw/simulation/enum.SimulationEvent.html\" title=\"enum libcw::simulation::SimulationEvent\">SimulationEvent</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libcw/simulation/enum.BuilderError.html\" title=\"enum libcw::simulation::BuilderError\">BuilderError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
